# Generated by Django 4.0.6 on 2022-07-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0004_rename_patient_patients_alter_patients_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='idade',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='sexo',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='telefone',
            new_name='phone',
        ),
    ]
