# Generated by Django 4.0.6 on 2022-07-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0006_patientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='height',
            field=models.FloatField(),
        ),
    ]
