# Generated by Django 4.0.6 on 2022-07-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0007_alter_patientdata_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('carbohydrates', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('grease', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlatForm.patients')),
            ],
        ),
        migrations.AlterModelOptions(
            name='patientdata',
            options={'verbose_name': 'PatientData', 'verbose_name_plural': 'PatientDatas'},
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='opcao')),
                ('description', models.TextField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlatForm.meal')),
            ],
        ),
    ]
